In [1]:
import pandas as pd

In [38]:
df=pd.read_csv('https://raw.githubusercontent.com/okravtsova123/ironhack_study/main/MidTermProject/rent.csv', sep=';')

In [51]:
df

,index,regio1,servicecharge,heatingtype,telekomtvoffer,newlyconst,balcony,pricetrend,noparkspaces,firingtypes,...,condition,petsallowed,lift,typeofflat,geo_plz,norooms,floor,numberoffloors,noroomsrange,garden
0,14,Nordrhein_Westfalen,215.0,gas_heating,ONE_YEAR_FREE,True,True,3.76,1.0,gas,...,first_time_use,negotiable,True,ground_floor,44229,3.0,0.0,4.0,3,False
1,77,Berlin,150.0,floor_heating,ONE_YEAR_FREE,True,True,6.60,1.0,district_heating,...,first_time_use,no,True,apartment,10179,2.0,3.0,5.0,2,False
2,130,Nordrhein_Westfalen,223.0,central_heating,ONE_YEAR_FREE,True,True,3.78,1.0,district_heating,...,mint_condition,no,True,roof_storey,33607,2.5,4.0,4.0,2,False
3,281,Bayern,190.0,central_heating,ONE_YEAR_FREE,True,True,5.08,1.0,gas,...,fully_renovated,no,True,maisonette,81476,1.5,2.0,3.0,1,False
4,366,Nordrhein_Westfalen,125.0,floor_heating,ONE_YEAR_FREE,True,True,4.24,1.0,gas,...,first_time_use,no,False,apartment,51427,3.0,1.0,2.0,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2709,268625,Bayern,160.0,floor_heating,ONE_YEAR_FREE,True,True,5.20,1.0,gas,...,first_time_use,no,True,apartment,91301,2.0,1.0,4.0,2,False
2710,268722,Sachsen,165.0,floor_heating,ONE_YEAR_FREE,True,True,4.87,1.0,district_heating,...,first_time_use,negotiable,True,apartment,4229,3.0,4.0,5.0,3,False
2711,268792,Bayern,310.0,floor_heating,ONE_YEAR_FREE,True,True,6.02,2.0,combined_heat_and_power_fossil_fuels,...,first_time_use,negotiable,True,roof_storey,91560,3.0,2.0,2.0,3,False
2712,268821,Rheinland_Pfalz,80.0,central_heating,ON_DEMAND,True,True,3.54,1.0,gas,...,first_time_use,no,False,apartment,56281,2.0,1.0,2.0,2,False
2713,268827,Niedersachsen,200.0,central_heating,ONE_YEAR_FREE,True,True,4.30,1.0,pellet_heating,...,first_time_use,no,True,apartment,30900,2.5,1.0,2.0,2,False

In [ ]:
#checking NAs
df.isna().sum()

In [40]:
# cleaning NAs
df=df.dropna()

In [41]:
#lowercasing all columnnames
df.columns=df.columns.str.lower()

In [42]:
# only new buildings
df=df[df['newlyconst']==True]

In [43]:
#reseting index
df=df.reset_index()

In [50]:
#checking NAs
df.isna().sum()

index             0
regio1            0
servicecharge     0
heatingtype       0
telekomtvoffer    0
newlyconst        0
balcony           0
pricetrend        0
noparkspaces      0
firingtypes       0
haskitchen        0
geo_bln           0
cellar            0
baserent          0
livingspace       0
geo_krs           0
condition         0
petsallowed       0
lift              0
typeofflat        0
geo_plz           0
norooms           0
floor             0
numberoffloors    0
noroomsrange      0
garden            0
dtype: int64

In [53]:
#checking unqiue values in hitting
df['heatingtype'].unique()

array(['gas_heating', 'floor_heating', 'central_heating',
       'combined_heat_and_power_plant', 'heat_pump', 'district_heating',
       'wood_pellet_heating', 'solar_heating',
       'self_contained_central_heating', 'stove_heating',
       'electric_heating', 'oil_heating'], dtype=object)

In [54]:
#checking unqiue values in coditions
df['condition'].unique()

array(['first_time_use', 'mint_condition', 'fully_renovated', 'well_kept',
       'first_time_use_after_refurbishment', 'refurbished', 'modernized'],
      dtype=object)

In [62]:
#unifying first time use and all refurbishement, modernization and renovation in 1 thing

def condition_clean(state):
        if 'first_time_use' in state:
            state='first_time_use'
        elif state=='fully_renovated' or state=='refurbished' or state=='modernized':
            state='refurbished'
        else:
            state=state
        return state
            
df['condition']=df['condition'].apply(condition_clean)

In [63]:
df=

,index,regio1,servicecharge,heatingtype,telekomtvoffer,newlyconst,balcony,pricetrend,noparkspaces,firingtypes,...,condition,petsallowed,lift,typeofflat,geo_plz,norooms,floor,numberoffloors,noroomsrange,garden
0,14,Nordrhein_Westfalen,215.0,gas_heating,ONE_YEAR_FREE,True,True,3.76,1.0,gas,...,first_time_use,negotiable,True,ground_floor,44229,3.0,0.0,4.0,3,False
1,77,Berlin,150.0,floor_heating,ONE_YEAR_FREE,True,True,6.60,1.0,district_heating,...,first_time_use,no,True,apartment,10179,2.0,3.0,5.0,2,False
2,130,Nordrhein_Westfalen,223.0,central_heating,ONE_YEAR_FREE,True,True,3.78,1.0,district_heating,...,mint_condition,no,True,roof_storey,33607,2.5,4.0,4.0,2,False
3,281,Bayern,190.0,central_heating,ONE_YEAR_FREE,True,True,5.08,1.0,gas,...,refurbished,no,True,maisonette,81476,1.5,2.0,3.0,1,False
4,366,Nordrhein_Westfalen,125.0,floor_heating,ONE_YEAR_FREE,True,True,4.24,1.0,gas,...,first_time_use,no,False,apartment,51427,3.0,1.0,2.0,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2709,268625,Bayern,160.0,floor_heating,ONE_YEAR_FREE,True,True,5.20,1.0,gas,...,first_time_use,no,True,apartment,91301,2.0,1.0,4.0,2,False
2710,268722,Sachsen,165.0,floor_heating,ONE_YEAR_FREE,True,True,4.87,1.0,district_heating,...,first_time_use,negotiable,True,apartment,4229,3.0,4.0,5.0,3,False
2711,268792,Bayern,310.0,floor_heating,ONE_YEAR_FREE,True,True,6.02,2.0,combined_heat_and_power_fossil_fuels,...,first_time_use,negotiable,True,roof_storey,91560,3.0,2.0,2.0,3,False
2712,268821,Rheinland_Pfalz,80.0,central_heating,ON_DEMAND,True,True,3.54,1.0,gas,...,first_time_use,no,False,apartment,56281,2.0,1.0,2.0,2,False
2713,268827,Niedersachsen,200.0,central_heating,ONE_YEAR_FREE,True,True,4.30,1.0,pellet_heating,...,first_time_use,no,True,apartment,30900,2.5,1.0,2.0,2,False